--- 
http_interactions: 
- request: 
    method: get
    uri: http://parse.name/names/parse.json?token=7d112490-ff1e-4759-9af1-a3b30a2cc87a&q=tyler+vannurden
    body: 
      string: ""
    headers: 
      timeout: 
      - "5"
      accept-encoding: 
      - gzip, deflate
      accept: 
      - "*/*; q=0.5, application/xml"
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      x-content-type-options: 
      - nosniff
      etag: 
      - W/"b9426689725a4e9720b2cc4f588ac486"
      x-runtime: 
      - "0.008652"
      date: 
      - Fri, 07 Jun 2019 18:54:31 GMT
      transfer-encoding: 
      - chunked
      x-powered-by: 
      - Phusion Passenger 5.3.4
      content-type: 
      - application/json; charset=utf-8
      x-request-id: 
      - 8446e9db-8ddc-4c09-8447-41cf0164e518
      status: 
      - 200 OK
      set-cookie: 
      - _parse_name_session=eGEwVmtZTmtjMjFZYVU0L2I5RUlJcXZLZkh5cnRGSnpvemtiemNoWXhMSHRCSGgwNW55R3l2NXpzaFU0WjVITUJjMzAwTkNNSG9EdW1Eb3VVYXhwRkxub3ZWM3lqQWF6bE04K1BnaU91aFNQWkdVVnFUMFh4ejZ2bk1SSGVWR0ItLTlSUmRDNmRVRG5vMHBPNFNHWVEvMlE9PQ%3D%3D--ba8ff9af8e0182507650a29b3bdd18369e5d54d6; path=/; HttpOnly
      cache-control: 
      - max-age=0, private, must-revalidate
      server: 
      - Apache/2.4.18 (Ubuntu)
      x-frame-options: 
      - SAMEORIGIN
      x-xss-protection: 
      - 1; mode=block
    body: 
      string: "{\"name_like_score\":2,\"id\":7439368,\"uuid\":\"edac9337-102a-4ed7-976b-e60b2eea6370\",\"language\":\"en\",\"input\":\"tyler vannurden\",\"parse_status\":200,\"parse_method\":\"R\",\"parser_version\":24,\"contains_aka_or_fka\":false,\"people_cache\":[{\"id\":444870,\"given_name\":\"Tyler\",\"surname\":\"Vannurden\",\"secondary_name\":\"\",\"suffix\":\"\",\"prefix\":\"\",\"salutation\":\"\",\"alternate_name\":\"\",\"credentials\":\"\",\"uuid\":\"337e1d81-5e98-4eda-921c-2d7bcf82f165\",\"language\":\"en\",\"gender\":null,\"created_by_user_id\":null,\"updated_by_user_id\":null,\"created_at\":\"2018-02-06T16:04:35.000Z\",\"updated_at\":\"2018-02-06T16:04:35.000Z\"}],\"organizations_cache\":[],\"job_titles_cache\":null,\"credentials_cache\":null,\"email_addresses_cache\":null,\"telephones_cache\":null,\"created_by_user_id\":null,\"updated_by_user_id\":null,\"created_at\":\"2019-02-01T04:06:47.000Z\",\"updated_at\":\"2019-02-01T04:06:47.000Z\"}"
    http_version: "1.1"
  recorded_at: Fri, 07 Jun 2019 18:54:31 GMT
recorded_with: VCR 2.9.2
